### ISSUE TITLE
Shading plugin

### ISSUE THREAD

**Issue by rexlManu** [JitseB/NPCLib#67]
Hello,

when im shading your plugin into mine for the library then the plugin.yml gets overrided by yours.
So i would suggest to add a module like npclib-library without spigot dummy stuff

**Comment by JitseB** [comment]
How are you shading my library? It shouldn’t override your plugin.yml in any case.
If you’re using Maven, you can just shade the `npclib-plugin` module. If you’re using the IntelliJ dependency shader, you can exclude the plugin.yml from the npclib-plugin.

The reason I have a plugin.yml in the library is so that people who aren’t able to shade the library (mostly developers who are using Eclipse and aren’t very experienced with Java), can just put the library in their plugins folder and it’ll load the classes automatically.

I could indeed put the class loader in a specific module, but I don’t think that’s necessary. Maybe I’ll do that for version 3.0.

**Comment by rexlManu** [comment]
I just adding your library as dependency with the scope "compile".

For shading im using the plugin maven-assembly-plugin with the configuration jar-with-dependencies (https://paste.it-lampe.de/sevax.xml).

**Comment by JitseB** [comment]
If you're not using any other features of the Maven assembly plugin, then you can just use the Maven shade plugin:
```Java
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by JitseB** [comment]
If that doesn't help your issue or if you're using the assembly plugin for good reason, I'll create a module for the class loader and create a new release for it.

**Comment by rexlManu** [comment]
Yea its working with this solution, but i would suggest to add a module only with the library and nms code^^

**Comment by JitseB** [comment]
Great! I’ll add the module sometime soon.
Closing issue.
