### ISSUE TITLE
NPC disappears

### ISSUE THREAD

**Issue by Exception426** [JitseB/NPCLib#70]
**Describe the bug**
My NPCs spawn but if I remove the default skin and another MineSkin, they will disappear after a while. Then when I move away from them and come back they are back. Please help

**NPCLib usage option**
NPCLib can be used in multiple ways, please provide [the number](https://github.com/JitseB/NPCLib#usage) corresponding to your usage option.

**NPCLib JAR name**
npclib-plugin-2.5.1-SNAPSHOT.jar

**Server version**
1.8.8

**Comment by JitseB** [comment]
Hi there, thanks for opening this issue ticket!
To help you any further, please provided me with the following information:
* What code are you using the manipulate and spawn the NPC?
* After about how long does the NPC disappear?
* What usage option did you use? (you didn't fill that in in the template)
There's a reason why I ask all the things in the template, next time you create an issue ticket, please follow them and don't remove questions you thing are unnecessary. 😛

**Comment by Exception426** [comment]
https://hasteb.in/ijetusog.java
My Code

Sometimes the NPC doesn't go away sometimes there is no set time.

**Comment by JitseB** [comment]
So, first you see it and then it disappears? The hologram is still visible, just not the NPC, right?

**Comment by Exception426** [comment]
Recognize both. And yes at the beginning I see him talking to BGHDDevelopment and they said I should create a problem

**Comment by Exception426** [comment]
Both will disappear *
sorry my english is bad. Im from germany

**Comment by JitseB** [comment]
Oh that’s actually a good thing. That’d mean it’s in the auto hiding system somewhere.
I’ll think about this problem for a bit, I’m rather busy tomorrow. I’ll have some time again the day after that.

**Comment by Exception426** [comment]
Hm okay. Thanks man.

**Comment by JitseB** [comment]
Note to self: The issue might exist because when the player gets in proximity of the NPC, its autospawn. `NPC#spawn` checks whether the player can actually see it using the dotproduct of the look direction. This might result in the system thinking it shouldn’t be testing for anymore.
Then the UUID of the player is in the `shown` set, but not in the `autohide` set anymore.

I think I have found the problem, but I’ll debug more in the day after tomorrow. 👍

**Comment by Exception426** [comment]
Can you fix the problem today?

**Comment by Exception426** [comment]
It would be important for me but you also have a life so please take your time as soon as possible

**Comment by JitseB** [comment]
No, NPCLib is a free resource and I will treat it as such. I’ll only work on it in my spare time. If you would like this issue to be solved sooner. You could always try to help me find the issue yourself and create a PR! :)

**Comment by JitseB** [comment]
What's the `view-distance` in your `server.properties`?

**Comment by Exception426** [comment]
10

**Comment by Exception426** [comment]
What does that have to do with it?

**Comment by Exception426** [comment]
Ahh it works with view-distance: 16!

**Comment by JitseB** [comment]
Yeah, there's a slight issue with the auto-hiding system. I can't seem to figure it out now. I'll continue on it tomorrow.
Turns out I have added some partial check in the player listener, but have not yet implemented these in the NPC class. Resulting in this strange behavior.

**Comment by Exception426** [comment]
Okay.

**Comment by Exception426** [comment]
The problem is there!

**Comment by Exception426** [comment]
The problem is back! **

**Comment by JitseB** [comment]
The issue should be fixed in v2.5.2-SNAPSHOT. You can download it here: https://github.com/JitseB/NPCLib/releases/tag/2.5.2-SNAPSHOT

I ended up reworking the entire auto-hiding system, I found some issues that gave false-positives; should be solved now. 

If your issue does come up again, feel free to comment here. Then I'll reopen the ticket.

Have a good day!
